CREATE SCHEMA IF NOT EXISTS misc;
--
-- Table creations
--
-- misc.quotes stores all quotes
CREATE TABLE misc.quotes (
    quote_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote text NOT NULL,
    description text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    created_by int REFERENCES people.users(user_id)
);
--
-- misc.webcams stores all webcams
CREATE TABLE misc.webcams (
    camera_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    url text NOT NULL,
    file text NOT NULL,
    mime_type text NOT NULL,
    enabled boolean NOT NULL DEFAULT FALSE,
    permission_id int REFERENCES people.permissions(permission_id),
    CONSTRAINT namechk CHECK (char_length(name) <= 20)
);
--
-- misc.teaching_periods term / semester dates
CREATE TABLE misc.teaching_periods (
    period_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year int NOT NULL,
    name text NOT NULL,
    start timestamptz NOT NULL,
    finish timestamptz NOT NULL,
    CONSTRAINT datechk CHECK (finish > start),
    CONSTRAINT peroidchk CHECK (name IN ('autumn', 'spring', 'summer'))
);
COMMENT ON COLUMN misc.teaching_periods.year IS 'The first year of the academic year i.e. 2021 if the academic year is 2021/2022'
COMMENT ON COLUMN misc.teaching_periods.start IS 'Midnight UTC, Monday Week 1';
COMMENT ON COLUMN misc.teaching_periods.finish IS 'Midnight UTC, Monday Week 11';
--
-- misc.redirects
CREATE TABLE misc.redirects (
    redirect_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url text NOT NULL UNIQUE,
    destination_url text NOT NULL,
    external bool DEFAULT FALSE
);
COMMENT ON COLUMN misc.redirects.destination_url IS
'URL path by default it is not external and just internal,
can be made external with the external flag';
