-- Creating event schema, all event calendar related tables are stored here
CREATE SCHEMA event;
-- We will initiate the tables in the following order:
-- 1. event.events REFERENCES people.users
-- 2. event.signups REFERENCES event.events
-- 3. event.positions REFERENCES people.permissions
-- 4. event.crew REFERENCES event.signups, event.positions, people.users
-- 5. event.attendees REFERENCES event.events, people.users
--
-- New tables
-- 7. event.groups
-- 6. event.rich_positions REFERENCES event.positions, event.groups
--
-- Table creations
--
-- event.events is a single event available on the calendar, contains signup sheets
CREATE TABLE event.events (
    event_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL DEFAULT 'other',
    name text NOT NULL,
    start_date timestamptz NOT NULL,
    end_date timestamptz NOT NULL,
    description text NOT NULL DEFAULT '',
    location text NOT NULL DEFAULT '',
    is_private boolean NOT NULL DEFAULT false,
    is_cancelled boolean NOT NULL DEFAULT false,
    is_tentative boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    created_by int REFERENCES people.users(user_id),
    updated_at timestamptz,
    updated_by int REFERENCES people.users(user_id),
    deleted_at timestamptz,
    deleted_by int REFERENCES people.users(user_id),
    CONSTRAINT namechk CHECK (char_length(name) <= 100),
    CONSTRAINT locationchk CHECK (char_length(location) <= 100)
);
COMMENT ON COLUMN event.events.event_type IS 'Can be show, meeting, social';
--
-- event.signups is a signup sheet for an event, contains the positions and who is signed up
CREATE TABLE event.signups (
    signup_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id int REFERENCES event.events(event_id) ON DELETE CASCADE,
    title text NOT NULL,
    description text NOT NULL DEFAULT '',
    unlock_date timestamptz,
    arrival_time timestamptz,
    start_time timestamptz,
    end_time timestamptz,
    CONSTRAINT titlechk CHECK (char_length(title) <= 50)
);
--
-- event.positions is each position that is available for a signup sheet i.e. cam-op
CREATE TABLE event.positions (
    position_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    admin boolean NOT NULL DEFAULT false,
    permission_id int REFERENCES people.permissions(permission_id),
    CONSTRAINT namechk CHECK (char_length(name) <= 40)
);
--
-- event.crew is the individual position on the signup sheet with the user.BIGINT
-- Whilst this is many to many we have an ID here since a signup can have multiple
-- of the same position
CREATE TABLE event.crews (
    crew_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signup_id int REFERENCES event.signups(signup_id) ON UPDATE CASCADE ON DELETE CASCADE,
    position_id int REFERENCES event.positions(position_id) ON UPDATE CASCADE ON DELETE CASCADE,
    user_id int REFERENCES people.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    credited boolean NOT NULL DEFAULT TRUE,
    locked bool NOT NULL DEFAULT false,
    ordering int NOT NULL
);
--
-- event.attendees maps the many to many relationship for socials / meetings
CREATE TABLE event.attendees (
    event_id int REFERENCES event.events(event_id) ON UPDATE CASCADE ON DELETE CASCADE,
    user_id int REFERENCES people.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    attend_status text NOT NULL,
    CONSTRAINT attendees_pkey PRIMARY KEY (event_id, user_id)
);
--
-- event.groups represents the organisational group a position is part of including a group leader
CREATE TABLE event.groups (
    group_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leader int REFERENCES people.users(user_id) ON UPDATE CASCADE,
    description text NOT NULL
);
COMMENT ON TABLE event.groups IS 'represents the organisational group a position is part of including a group leader';
--
-- event.rich_positions adds extra metadata to an existing position. Used for the more common roles, to help
-- provide further information about a position
CREATE TABLE event.rich_positions (
    position_id int REFERENCES event.positions(position_id) ON UPDATE CASCADE ON DELETE CASCADE,
    group_id int REFERENCES event.groups(group_id) ON UPDATE CASCADE,
    difficulty int NOT NULL,
    description text NOT NULL,
    image text NOT NULL,
    training text NOT NULL,
    resources text [] NOT NULL,
    CONSTRAINT rich_positions_pkey PRIMARY KEY (position_id)
);
COMMENT ON TABLE event.rich_positions IS 'adds extra metadata to an existing position. Used for the more common roles, to help 
provide further information about a position';
COMMENT ON COLUMN event.rich_positions.description IS 'Whilst a normal position already includes a description, this goes into a lot more detail
and will have it''s own dedicated page for this to be displayed instead of a hover-over';
COMMENT ON COLUMN event.rich_positions.training IS 'Will be a URL to its wiki page / training video but displayed as a button to the user';
COMMENT ON COLUMN event.rich_positions.resources IS 'this would be to include useful articles, resources, videos, etc for this position. 
Probably keeping links formatted as markdown to keep the schema simple?';
--
-- event.projects allows events to be grouped up under one entity, useful for multi-day events
-- we might be able to just have tags on events instead?
CREATE TABLE event.projects (
    project_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL,
    start_date timestamptz NOT NULL,
    end_date timestamptz NOT NULL
);
