CREATE SCHEMA misc;
--
-- Table creations
--
-- internal.quotes stores all quotes
CREATE TABLE misc.quotes (
    quote_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote text NOT NULL,
    description text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    created_by int REFERENCES people.users(user_id)
);
--
-- Migrations
--
-- Migrate public.quotes to internal.quotes
INSERT INTO misc.quotes (
        quote_id,
        quote,
        description,
        created_at,
        created_by
    )
SELECT id,
    quote,
    COALESCE(description, ''),
    posted_date,
    posted_by
FROM public.quotes;