CREATE SCHEMA misc;
--
-- Table creations
--
-- misc.quotes stores all quotes
CREATE TABLE misc.quotes (
    quote_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote text NOT NULL,
    description text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    created_by int REFERENCES people.users(user_id)
);
--
-- misc.webcams stores all webcams
CREATE TABLE misc.webcams (
    camera_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    url text NOT NULL,
    file text NOT NULL,
    mime_type text NOT NULL,
    enabled boolean NOT NULL DEFAULT FALSE,
    permission_id int REFERENCES people.permissions(permission_id),
    CONSTRAINT namechk CHECK (char_length(name) <= 20)
);
--
-- misc.terms term dates
CREATE TABLE misc.terms (
    term_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year int NOT NULL,
    term text NOT NULL,
    start timestamptz NOT NULL,
    finish timestamptz NOT NULL,
    CONSTRAINT datechk CHECK (finish > start),
    CONSTRAINT termchk CHECK (term IN ('autumn', 'spring', 'summer'))
);
COMMENT ON COLUMN misc.terms.start IS 'Midnight UTC, Monday Week 1';
COMMENT ON COLUMN misc.terms.finish IS 'Midnight UTC, Monday Week 11';
--
-- misc.redirects
CREATE TABLE misc.redirects (
    redirect_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url text NOT NULL UNIQUE,
    destination_url text NOT NULL,
    external bool DEFAULT FALSE
);
COMMENT ON COLUMN misc.redirects.destination_url IS
'URL path by default it is not external and just internal,
can be made external with the external flag';
--
-- Migrations
--
-- Migrate public.quotes to misc.quotes
INSERT INTO misc.quotes (
        quote_id,
        quote,
        description,
        created_at,
        created_by
    )
SELECT id,
    quote,
    COALESCE(description, ''),
    posted_date,
    posted_by
FROM public.quotes;
--
-- Migrate public.term_dates to misc.terms
INSERT INTO misc.terms (
    year,
    term,
    start,
    finish
)
SELECT year,
    term,
    start_date,
    start_date + interval '10 week'
FROM public.term_dates;
--
-- Migrate public.permalinks to misc.redirects
INSERT INTO misc.redirects(
    redirect_id, source_url, destination_url
)
SELECT id,
    permalink,
    real_url
FROM public.permalinks;