CREATE SCHEMA misc;
--
-- Table creations
--
-- misc.quotes stores all quotes
CREATE TABLE misc.quotes (
    quote_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote text NOT NULL,
    description text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    created_by int REFERENCES people.users(user_id)
);
--
-- misc.webcams stores all webcams
CREATE TABLE misc.webcams (
    camera_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    url text NOT NULL,
    enabled boolean NOT NULL DEFAULT FALSE,
    permission_id int REFERENCES people.permissions(permission_id),
    CONSTRAINT namechk CHECK (char_length(name) <= 20)
);
--
-- Migrations
--
-- Migrate public.quotes to misc.quotes
INSERT INTO misc.quotes (
        quote_id,
        quote,
        description,
        created_at,
        created_by
    )
SELECT id,
    quote,
    COALESCE(description, ''),
    posted_date,
    posted_by
FROM public.quotes;